---
kind: pipeline
type: kubernetes
name: testing

platform:
  os: linux
  arch: amd64

steps:
- name: test
  # do nothing
  pull: if-not-exists
  image: alpine/git
trigger:
  event:
  - pull_request

---
kind: pipeline
type: kubernetes
name: build

platform:
  os: linux
  arch: amd64

steps:
- name: find_packages
  pull: if-not-exists
  image: alpine/git
  commands:
    - ./build.sh find_packages
- name: build
  pull: always
  image: pcmid/arch-builder
  environment:
    SRCDEST: /packages
  commands:
    - ./build.sh
  when:
    branch:
      package/*

trigger:
  event:
  - pull_request
