---
kind: pipeline
type: kubernetes
name: test

platform:
  os: linux
  arch: amd64

steps:
- name: test
  # do nothing
  pull: if-not-exists
  image: alpine/git
trigger:
  event:
  - push
  - pull_request

---
kind: pipeline
type: kubernetes
name: build

platform:
  os: linux
  arch: amd64

steps:
- name: find_packages
  pull: if-not-exists
  image: alpine/git
  commands:
  - ./build.sh find_packages
  when:
    branch:
    - package/*

- name: build
  pull: always
  image: pcmid/arch-builder
  environment:
    SRCDEST: /packages
  commands:
  - ./build.sh
  when:
    branch:
    - master

trigger:
  event:
  - push
  - pull_request

depends_on:
  - test
